# Generated by Django 2.2.17 on 2023-05-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='top_level_domain',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
